
[server]
root = "./web/mnt"
audioExt = [
  ".wav",
  ".webm",
  ".opus",
  ".ogg",
  ".mp3",
  ".m4a",
  ".flac"
]
urlPrefix = "/MusicServer"

[database]
host = ["127.0.0.1:27017"]
dbName = "playerSongList"